### ISSUE TITLE
Anyway to repeat playing the sound.mp3 in the demo?

### ISSUE THREAD

**Issue by ykyuen** [CaffeinaLab/SiriWaveJS#10]
http://blog.kidliaa.com/demo/siri%20wave/

thx

**Comment by kopiro** [comment]
The demo is not written by our Team. :)

**Comment by ykyuen** [comment]
No problem. thx for your quick reply. =)

**Comment by kopiro** [comment]
You can ask to @liaa, anyway :)

**Comment by timi-codes** [comment]
@kopiro It seems this website expired http://blog.kidliaa.com/demo/siri%20wave/. I would like to know how to generate siriwave based on audion streamUrl.
