### ISSUE TITLE
Android WebView

### ISSUE THREAD

**Issue by jpatel888** [caffeinalab/siriwavejs#13]
Hi, I'm using the Siriwave in an application and i need it to look still like no one is speaking. I tried doing changing the amplitude and the speed to .01 but the speed didn't change. Any ideas? The speed attribute seems to be unresponsive.

**Comment by webdevninja** [comment]
Also any ideas on how to change the amplitude while it's moving? My app uses the microphone and I want siriwave to be responsive?

**Comment by kopiro** [comment]
Hello!

You've to use the methods `setSpeed(newValue)` and `setAmplitude(newValue)`.

**Comment by SmashedBird** [comment]
Good morning, I'm trying to change the amplitude on hover but so far I cannot figure out how to change the amplitude without creating a new wave. Here is my code :

![image](https://cloud.githubusercontent.com/assets/5365868/16422294/816ca606-3d1d-11e6-9620-74bf3e7875bd.png)

I would really appreciate if any of you could give me a little help.
Than you

**Comment by kopiro** [comment]
Can you post the code, please ? :)

**Comment by SmashedBird** [comment]
Hey, Thank you for your help. I created a pen :
[http://codepen.io/BastienAustin/pen/PzmaNg](http://codepen.io/BastienAustin/pen/PzmaNg)

**Comment by kopiro** [comment]
Okay.. 

```
SW.setAmplitude( .... );
```

not?
