### ISSUE TITLE
How to draw a straight line before and after a wave using siriwave.js

### ISSUE THREAD

**Issue by mikl31** [CaffeinaLab/SiriWaveJS#8]
I've an issue using siriwave.js, I would like to have a line then the canvas which contains the wave but my problem is that the begin (at the left) and the end (at the right) of the wave both move. It result that I can't give a sense of continuity between my line and the canvas.

Here's a link to illustrate my problem :
http://stackoverflow.com/questions/31235493/how-to-draw-a-straight-line-before-and-after-a-wave-using-siriwave-js

Does anyone knows how to fix that ? Many thanks

**Comment by kopiro** [comment]
We edited the *global attenuation function* to return values near to the 0, 
and hard-coded X values near to `2` to this: 

```js
if (Math.abs(i) >= 1.90) y = this.height_2;
```

**Comment by mikl31** [comment]
Thank you very much !!!!!
